/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HotelMgt;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;


@SpringBootTest
public class LibraryTest {
    @Test
    void contextLoads() {
    	
    }
}